### ISSUE TITLE
Kosinski compression takes a long time if there's a long string of repeated bytes

### ISSUE THREAD

**Issue by DevsArchive** [MainMemory/FW-KENSC-ShellExt#6]
Let's say there's a long repeated string of 00s, which is what one of the files I have to compress to Kosinski has multiple of. The time it takes to compress it takes far too long to the point it causes Windows Explorer to stop responding.

**Comment by Clownacy** [comment]
> Probably related to [this issue](https://github.com/sonicretro/KENSSharp/issues/6),?

Nah, KENSSharp uses some ported logic from my clownlzss project, while this uses flamewing's KENSC/mdcomp. KENSSharp is slow because the compression algorithm that it's using doesn't seem to agree with C#, while this sounds like it's down to a bug in the old version of KENSC that's being used.

If I remember right, I once considered updating KENSC, but, at the time, upstream KENSC had introduced a dependency on the Boost library or a cutting-edge version of C++ or something. Either way, I couldn't update KENSC.

**Comment by DevsArchive** [comment]
Yeah, I realized that mistake and edited it out. I'm going to see if I can implement the updated version myself. Regarding Boost, it looks like it's only really in the big endian I/O stuff.

**Comment by DevsArchive** [comment]
Got it to compile with the new mdcomp. And yeah, there's substantially better performance.

**Comment by Clownacy** [comment]
FW-KENSC was updated in 4188f3cb44d75271c7ff9ce1906adaeb553793d9.
